variables:
  DOCKER_IMAGE: binarrshina/goods-api

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: docker:20.10
  services:
    - docker:dind
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:latest
  only:
    - main

tests:
  stage: test
  image: python:3.11-slim
  script:
    - pip install poetry
    - poetry install --no-interaction --no-root
    - |
      if [ -d "tests" ] && [ "$(ls -A tests)" ]; then
        poetry run pytest
      else
        echo "No tests found. Skipping pytest."
      fi
  only:
    - main

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - echo "Connecting to $SERVER_USER@$SERVER_IP"
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
  script:
    - ssh $SERVER_USER@$SERVER_IP "docker pull $DOCKER_IMAGE:latest && cd /root/projects/goods-api && docker-compose up -d"
  only:
    - main
