version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: goods-api-app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/goods_db
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  db:
    image: postgres:15
    container_name: goods-api-db
    environment:
      POSTGRES_USER: goods_user
      POSTGRES_PASSWORD: goods_user12345!
      POSTGRES_DB: goods_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goods_user -d goods_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
