services:
  api:
    image: binarrshina/goods-api:latest  # ← вместо build
    ports:
      - "8000:8000"
    container_name: goods-api-app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    restart: always
